### ISSUE TITLE
Crash when going to certain places (mineshaft chest contents generation?)

### ISSUE THREAD

**Issue by TheEvilPenguin** [mobehun/BraveTechnology#5]
I've been getting crashes in the most recent version when going to certain places in certain maps - it seems to be related to generating random inventory for mineshaft chests.

Reproduction steps:
Create a new world with seed 610963551160096897
Travel straight East to roughly 300, 870

It seems to be a bug in some mod, as I tried adding all the same mods to a fresh instance and I had the same problem.

I've attached the full crash log, but the relevant part seems to be:
[crash-2016-10-07_13.29.59-server.txt](https://github.com/mobehun/BraveTechnology/files/515143/crash-2016-10-07_13.29.59-server.txt)

java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.minecraft.world.storage.loot.LootPool.func_186452_a(LootPool.java:60)
    at net.minecraft.world.storage.loot.LootPool.func_186449_b(LootPool.java:83)
    at net.minecraft.world.storage.loot.LootTable.func_186462_a(LootTable.java:42)
    at net.minecraft.world.storage.loot.LootTable.func_186460_a(LootTable.java:57)
    at net.minecraft.tileentity.TileEntityLockableLoot.func_184281_d(SourceFile:55)
    at net.minecraft.tileentity.TileEntityChest.func_70301_a(TileEntityChest.java:58)
    at net.minecraft.inventory.InventoryHelper.func_180174_a(InventoryHelper.java:28)
    at net.minecraft.inventory.InventoryHelper.func_180175_a(InventoryHelper.java:16)
    at net.minecraft.block.BlockChest.func_180663_b(BlockChest.java:382)
    at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:565)
    at net.minecraft.world.World.func_180501_a(World.java:331)
    at net.minecraft.world.gen.structure.StructureComponent.func_175811_a(StructureComponent.java:240)
    at net.minecraft.world.gen.structure.StructureComponent.func_175804_a(StructureComponent.java:292)
    at net.minecraft.world.gen.structure.StructureMineshaftPieces$Corridor.func_74875_a(SourceFile:449)
[snip]

**Comment by TheEvilPenguin** [comment]
I think I've narrowed it down to Enchanting Plus, Ender Storage or Ender Zoo

**Comment by mobehun** [comment]
Then it's probably Enchanting Plus. It generates abandoned loot. I'll figure something out soon.

**Comment by mobehun** [comment]
https://github.com/Darkhax-Minecraft/Enchanting-Plus/issues/47

**Comment by mobehun** [comment]
Should be fixed with the new version.
